name: Credit Card Service CI/CD

on:
  push:
    branches:
      - master
      - develop
      - cicd
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Buiding the project
        run: dotnet build --no-restore
